# /etc/fail2ban/action.d/ufw-telemt.conf
# Прямой бан через iptables в цепочку INPUT

[Definition]
actionstart = iptables -N f2b-telemt 2>/dev/null || true
              iptables -I INPUT -j f2b-telemt

actionstop  = iptables -D INPUT -j f2b-telemt 2>/dev/null || true
              iptables -F f2b-telemt 2>/dev/null || true
              iptables -X f2b-telemt 2>/dev/null || true

actionban   = iptables -I f2b-telemt 1 -s <ip> -j DROP

actionunban = iptables -D f2b-telemt -s <ip> -j DROP

[Init]
