# /etc/fail2ban/jail.d/telemt-bad-fp.conf

[telemt-bad-fp]
enabled  = true
backend  = polling

filter   = telemt-bad-fp
logpath  = /var/log/telemt-bad-fp.log

bantime  = 3600
findtime = 600
maxretry = 1

action   = ufw-telemt
